version: 2
jobs:
  build:
    working_directory: ~/loguehub
    docker:
      - image: circleci/python:3.6.4
        environment:
          PIPENV_VENV_IN_PROJECT: true
          DATABASE_URL: postgresql://admin001@localhost/logue_db?sslmode=disable
      - image: circleci/postgres:9.6.2
        environment:
          POSTGRES_USER: admin001
          POSTGRES_DB: logue_db
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
      - run:
          command: |
            sudo pip install pipenv
            pipenv install
      - run:
          command: |
            pipenv run "python manage.py test"
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: tr1
      - add_ssh_keys:
          fingerprints:
          - "ioGb2l+7ryraXRjpmfbTdLu1Q7b+W7plg8XcZURAYtQ"
      - deploy:
          name: Deploy Master to Heroku
          command: |
              git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master